# PsalmPonder Word List - Words taken from Psalms
word_list = [
    'psalm', 'praise', 'worship', 'god', 'lord', 'heaven', 'earth', 'sing', 'joy', 'heart', 'faith', 'trust', 'hope',
    'bless', 'righteous', 'grace', 'mercy', 'love', 'soul', 'spirit', 'holy', 'sanctuary', 'salvation', 'redeem',
    'victory', 'glory', 'mighty', 'strength', 'shield', 'deliver', 'peace', 'joyful', 'triumph', 'truth', 'light',
    'guide', 'refuge', 'rock', 'fortress', 'shepherd', 'healer', 'provider', 'almighty', 'eternal', 'king', 'creator',
    'sovereign', 'exalt', 'majesty', 'grateful', 'thanksgiving', 'bountiful', 'hallelujah', 'honor', 'rejoice', 'adore',
    'compassion', 'forgive', 'redeemer', 'awesome', 'covenant', 'hopeful', 'faithful', 'gracious', 'counselor',
    'righteousness', 'restoration', 'forgiveness', 'repentance', 'glorious', 'holiness', 'abundant', 'proclaim',
    'exaltation', 'sanctify', 'lament', 'intercede', 'providence', 'intercession', 'prophecy', 'faithfulness', 'revive',
    'exhort', 'joyous', 'faithfully', 'worshipper', 'devotion', 'hallowed', 'sanctified', 'glorified', 'exalted',
    'praiseworthy', 'sacred', 'hymn', 'melody', 'meditate', 'veneration', 'testimony', 'trinity', 'magnify', 'beatitude',
    'adoration', 'reverence', 'testament', 'alleluia', 'shekinah', 'psalter', 'ascend', 'cherubim', 'temple', 'sacrament',
    'purify', 'oracle', 'prayerful', 'anointed', 'paraclete', 'devotional', 'sabbath', 'liturgy', 'exhortation',
    'atonement', 'sanctification', 'revelation', 'tranquility', 'benediction', 'communion', 'lamentation', 'oblation',
    'blessedness', 'ascent', 'hearken', 'bethel', 'exultation', 'liturgical', 'anointing', 'orthodoxy', 'theology',
    'homily', 'sacramental', 'solace', 'incense', 'absolution', 'advent', 'nativity', 'epiphany', 'penitence', 'triumphal',
    'pilgrimage', 'theophany', 'transcendence', 'gratitude', 'rejoicing', 'exodus', 'deliverance', 'promised', 'redemption',
    'celestial', 'graceful', 'meditation', 'majestic', 'trusting', 'serenity', 'celebration', 'illumination', 'spiritual',
    'guidance', 'blessings', 'heavenly', 'worshipful', 'harmony', 'meditative', 'reflection', 'inspiration', 'glorification',
    'eternity', 'psalmist', 'trustworthy', 'people', 'against', 'great', 'forever', 'loyal', 'enemies', 'right', 'turned',
    'director', 'steadfast', 'power', 'loving-kindness', 'thine', 'things', 'every', 'good', 'land', 'look', 'song',
    'kindness', 'word', 'given', 'name', 'among', 'indeed', 'chief', 'though', 'without', 'makes', 'gives', 'unfailing',
    'voice', 'interlude', 'mind', 'pause', 'didst', 'saying', 'surely', 'wilt', 'haters', 'stand', 'calmly', 'praises',
    'unchanging', 'afflicted', 'saving', 'clear', 'dwell', 'established', 'followers', 'remain', 'myself', 'takes',
    'destroyed', 'lives', 'observe', 'servant', 'endures', 'adversaries', 'commandments', 'descendants', 'foes', 'open',
    'answer', 'waters', 'always', 'iniquity', 'commands', 'delivered', 'distress', 'gentiles', 'everything', 'oppressed',
    'person', 'favor', 'overseer', 'times', 'send', 'attention', 'evil-doers', 'peoples', 'throughout', 'yourself', 'decrees',
    'midst', 'memory', 'night', 'pleasure', 'protect', 'shelter', 'troubled', 'understand', 'greatly', 'humankind', 'judge',
    'remember', 'standing', 'thank', 'thyself', 'young', 'concerning', 'generation', 'return', 'secure', 'slave', 'sorrow',
    'angry', 'covered', 'decisions', 'giving', 'sound', 'humbled', 'others', 'placed', 'promise', 'quickly', 'watch',
    'amazing', 'crushed', 'enemy', 'heathen', 'looking', 'overcome'
]